// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCyW9gtKTOSXSdFuQlqN1wcoouTEKrd4',
    appId: '1:660239780604:web:bd0f9dd8851df18c856579',
    messagingSenderId: '660239780604',
    projectId: 'farmagrotech-7d3a7',
    authDomain: 'farmagrotech-7d3a7.firebaseapp.com',
    databaseURL: 'https://farmagrotech-7d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'farmagrotech-7d3a7.firebasestorage.app',
    measurementId: 'G-92B8LQW6S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdyy7XT5YEIxvbS4GQ1Yb-7i-CSq1TUk',
    appId: '1:660239780604:android:bf87ffcf9f881569856579',
    messagingSenderId: '660239780604',
    projectId: 'farmagrotech-7d3a7',
    databaseURL: 'https://farmagrotech-7d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'farmagrotech-7d3a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkF_sFRPcUihvKHdEOTvkCShDZxPHu63w',
    appId: '1:660239780604:ios:06e309eee6cadb5d856579',
    messagingSenderId: '660239780604',
    projectId: 'farmagrotech-7d3a7',
    databaseURL: 'https://farmagrotech-7d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'farmagrotech-7d3a7.firebasestorage.app',
    iosBundleId: 'com.example.farmAgroTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkF_sFRPcUihvKHdEOTvkCShDZxPHu63w',
    appId: '1:660239780604:ios:06e309eee6cadb5d856579',
    messagingSenderId: '660239780604',
    projectId: 'farmagrotech-7d3a7',
    databaseURL: 'https://farmagrotech-7d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'farmagrotech-7d3a7.firebasestorage.app',
    iosBundleId: 'com.example.farmAgroTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBCyW9gtKTOSXSdFuQlqN1wcoouTEKrd4',
    appId: '1:660239780604:web:a11df713dac332a5856579',
    messagingSenderId: '660239780604',
    projectId: 'farmagrotech-7d3a7',
    authDomain: 'farmagrotech-7d3a7.firebaseapp.com',
    databaseURL: 'https://farmagrotech-7d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'farmagrotech-7d3a7.firebasestorage.app',
    measurementId: 'G-31W7QTE639',
  );
}
